### ISSUE TITLE
[FEATURE REQUEST] Add support for multiple schema formats

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/asyncapi#113]
**Is your feature request related to a problem? Please describe.**
Some users complain because they're already using Avro or Google's protobuf, and don't want to maintain the definitions in both formats, e.g., protobuf and JSON schema. Users want to reuse their definitions without having to make weird tricks.

**Can't it be tackled using specification extensions?**
Absolutely. But it would require having schemas defined as "empty objects" and then a specification extension providing the real value. While this is possible, it's a weird trick, because the JSON schema definition doesn't match the, for instance, protobuf definition.

**Describe the solution you'd like**
See the proposal below.

**Describe alternatives you've considered**
Using specification extensions.

**Additional context**
Unlike HTTP APIs, message-oriented architectures use a wide variety of protocols and message formats. We should embrace them and don't stick too heavily to JSON schema.

# Proposal

My proposal is to insert a new key into `headers` and `payload`. The key name will represent the schema format and its value will depend on the schema format.

##### Examples

```yaml
channels:
  user/created:
    subscribe:
      headers:
        application/x-protobuf: >
          message Headers {
            string my-app-header = 1;
          }
      payload:
        application/x-protobuf: >
          message UserCreated {
            int32 id = 1;
            string name = 2;
            string email = 3;
          }
```

Same document but using $ref's.

```yaml
channels:
  user/created:
    subscribe:
      headers:
        application/x-protobuf:
          $ref: 'path/to/user-created.proto#Headers'
      payload:
        application/x-protobuf:
          $ref: 'path/to/user-created.proto#UserCreated'
```

Specifying multiple schema formats is forbidden. The following is **NOT VALID**:

```yaml
channels:
  user/created:
    subscribe:
      headers:
        application/x-protobuf:
          $ref: 'path/to/user-created.proto#Headers'
      payload:
        application/x-protobuf:
          $ref: 'path/to/user-created.proto#UserCreated'
        application/schema+json;version=draft-07:
          $ref: 'path/to/user-created.json'
        application/vnd.oai.openapi;version=3.0.1#/components/schemas/UserCreated:
          $ref: 'path/to/user-created.json'
        avro:
          $ref: 'path/to/user-created.avro'
```

Notice the usage of URI fragments to point to a specific Proto message.

---

## Discarded solutions

Other solutions have been considered but discarded:

```yaml
channels:
  user/created:
    subscribe:
      schemaType: 'application/x-protobuf'
      headers:
        $ref: 'path/to/user-created.proto#headers'
      payload:
        $ref: 'path/to/user-created.proto#payload'
```

```yaml
channels:
  user/created:
    subscribe:
      headers:
        schemaType: 'application/x-protobuf'
        uri: 'path/to/user-created.proto#headers'
      payload:
        schemaType: 'application/x-protobuf'
        uri: 'path/to/user-created.proto#payload'
```
