### ISSUE TITLE
Gitter streaming example is incorrect

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/asyncapi#205]
Gitter streaming example is incorrect: https://github.com/asyncapi/asyncapi/blob/master/examples/next/gitter-streaming.yml#L53

Instead of:
```yaml
payload:
  'application/schema+json;version=draft-07':
    type: object
  ...
```

It should be:
```yaml
schemaFormat: 'application/schema+json;version=draft-07'
payload:
  type: object
  ...
```
