### ISSUE TITLE
[BUG] 'servers' examples in AsyncAPI 2.0.0 contain list of server objects instead of the map

### ISSUE THREAD

**Issue by kubaodias** [asyncapi/asyncapi#271]
**Describe the bug**
 ‘servers’ examples in https://www.asyncapi.com/docs/specifications/2.0.0/#serversObject contain list of server objects instead of the map i.e.
```
servers:
- url: development.gigantic-server.com
  description: Development server
  protocol: amqp
  protocolVersion: 0.9.1
- url: staging.gigantic-server.com
  description: Staging server
  protocol: amqp
  protocolVersion: 0.9.1
- url: api.gigantic-server.com
  description: Production server
  protocol: amqp
  protocolVersion: 0.9.1
```
