### ISSUE TITLE
Question: Kafka Config

### ISSUE THREAD

**Issue by gexclaude** [asyncapi/asyncapi#279]
We are experimenting with AsyncAPI for the use with Kafka. The following is a snippet of our example AsyncAPI document with a few question. Would be great if you could give quick hints if we are missing something.

```yml
**channels:**
  kafka.watchdog.heartbeat:
    description: Heartbeat topic
    subscribe:
      summary: Subscribe to watchdog-heartbeat
      operationId: subscribeWatchdogHeartbeat
#How do I specify configuration properties (https://kafka.apache.org/documentation/#consumerconfigs) of my consumer? E.g. maybe we need a specific "key.deserializer" in order to consume messages.
      traits:
        - $ref: '#/components/operationTraits/kafka'
      message:
        $ref: '#/components/messages/heartbeat'
    publish:
#How do I specify configuration properties (https://kafka.apache.org/documentation/#producerconfigs) of my producer? E.g. maybe we need to specify "acks" in order to produce correctly
      summary: Publish watchdog-heartbeats
      operationId: publishWatchdogHeartbeat
      traits:
        - $ref: '#/components/operationTraits/kafka'
#We could have a schema registry in Kafka. Could I link this registry?
      message:
        $ref: '#/components/messages/heartbeat'
#How do I specify kafka-streams application?```

**Comment by fmvilas** [comment]
Hey @gexclaude. When documenting kafka-specific properties, you have to use the kafka binding. It's currently under development so feel free to make proposals here: https://github.com/asyncapi/bindings/tree/master/kafka.

> We could have a schema registry in Kafka. Could I link this registry?

Sure you can. Should be something like this:

```yaml
message:
  payload:
    $ref: http://url-to-your-registry.com/your-message-payload.json
```

Or like this if you're using Avro (however tooling is not yet ready):

```yaml
message:
  schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
  payload:
    $ref: http://url-to-your-registry.com/your-message-payload.avsc
```

> How do I specify kafka-streams application?

You would have to be more specific with this question :)
