### ISSUE TITLE
Better way to define schemes, host and port

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/asyncapi#28]
Right now you can define the host and schemes your API supports the following way:

```yaml
host: api.company.com
schemes:
  - amqp
  - mqtt
```

However, most of the times the schemes are on different ports than the default ones. Or even in different hosts. We should be able to specify how and where to connect with each of the schemes.

Proposal:

```yaml
schemes:
  amqp:
    host: api.company.com
    port: 1122
  mqtt:
    host: api.company.com
    port: 5676
```

It will allow us to include more valuable information too, i.e.:

```yaml
schemes:
  mqtt:
    host: api.company.com/{app-id}
    port: 5676
    description: Allows you to connect using the MQTT protocol.
    parameters:
      app-id:
        description: You can find your `app-id` in our control panel, under the auth tab.
        required: true
        in: path
      token:
        description: You can find or generate your API `token` in our control panel, under the auth tab. If the token is not specified you'll only have subscribe permissions.
        required: false
        in: query
```

What do you think?

**Comment by fmvilas** [comment]
@MikeRalphson this is interesting for you as it would break [Widdershins](https://github.com/Mermade/widdershins).

**Comment by MikeRalphson** [comment]
@fmvilas obviously I'm happy to follow the spec!

Is there any benefit in tracking a little closer to the way OpenAPI 3.0.x does it? Something like:

```yaml
servers:
- url: //api.company.com/{app-id}:{port}
  description: Allows you to connect using the MQTT protocol.
  scheme: mqtt
  variables:
    app-id:
      default: demo
      description: You can find your `app-id` in our control panel, under the auth tab.
    port:
      enum:
        - '5676'
        - '5677'
      default: '5676'
```

Thus only the `scheme` property is different, as it doesn't represent a url protocol.
