### ISSUE TITLE
[FEATURE REQUEST] More defined data types

### ISSUE THREAD

**Issue by prdatur** [asyncapi/asyncapi#303]
**Is your feature request related to a problem? Please describe.**
Can not define my property.

**Can't it be tackled using specification extensions?**
No

**Describe the solution you'd like**
Adding additional data types.

| Common Name | type      | format | Comments                                     |
| :--                       | :--         | :--        | :--                                                   |
| timestamp          | integer | int32    | Seconds after unix epoch              |
| timestamp_ms   | long     | int64    | Milliseconds after unix epoch        |
| null                     | null      | null      | Programs can check for null value |

**Describe alternatives you've considered**
-

**Additional context**

I know it is a bit confusing why `null` should be included. Let me explain it by an example:

```yaml
x-response:
    oneOf:
    - $ref: '#/components/messages/get-version/response/ack'
    - $ref: '#/components/messages/get-version/response/status'
    - $ref: '#/components/messages/get-version/response/response'
```

Each response has the same "basic" properties.

```yaml
response:
    ack:
        summary: Publish status events
        description: This message will be published for acknowledge responses.
        payload:
            type: object
            required:
                - status
                - type
                - data
            properties:
                status: 
                    type: string
                    enum:
                    - error
                    - ok
                type:
                    type: string
                    description: The response type of the event.
                    enum:
                    - ack
                data:
                    type: null

    status:
        summary: Publish status events
        description: This message will be published for status responses.
        payload:
            type: object
            required:
                - status
                - type
                - data
            properties:
                status: 
                    type: string
                    enum:
                    - error
                    - ok
                type:
                    type: string
                    description: The response type of the event.
                    enum:
                    - status
                data:
                    @ref: "#/components/schemas/IGetVersionResponse"

    response:
        summary: Publish status events
        description: This message will be published for **response** responses.
        payload:
            type: object
            required:
                - status
                - type
                - data
            properties:
                status: 
                    type: string
                    enum:
                    - error
                    - ok
                type:
                    type: string
                    description: The response type of the event.
                    enum:
                    - response
                data:
                    type: array
                    items:
                        @ref: "#/components/schemas/IGetVersionResponse"
                message:
                    type: string
                    description: If present it holds the error message, will ony be send on error
```
As in this example the basic response is always the same, but the data will change depending on the provided `type`

Additional, I think 3 more types will not hurt the definition.

**Comment by fmvilas** [comment]
Hi @prdatur. AsyncAPI relies on JSON Schema for the data types. I guess you should ask for this in the JSON Schema project.

If you really need it now, a specification extension will suffice:

```yaml
...
type: integer
x-format: timestamp
```

Hope it helps!
