### ISSUE TITLE
[BUG] Unable to describe header for security scheme http when using a bearer token

### ISSUE THREAD

**Issue by luca-moser** [asyncapi/asyncapi#307]
**Describe the bug**
The current specification doesn't support describing the header name under which a bearer token will be supplied to the given server route.

When using for example a JWT like so:
```
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
```

and declaring it as a `security` in a server component like this:
```
servers:
  backend:
    url: /ws
    protocol: ws
    description: Backend WebSocket API Route
    security:
      - bearerAuth: []
```

The editor will render following:
![image](https://user-images.githubusercontent.com/1385611/72884506-86ddc380-3d06-11ea-8558-b09e678b9209.png)

Where then one is unable to declare for example `Authorization` as the header name which carries the bearer token, as a security schema of type `http` doesn't support the `name` and `in` properties.

**To Reproduce**
1. Use above YAML snippets
2. let it render in the AsyncAPI editor

**Expected behavior**
There should be a way to declare the header name or per default use `Authorization`.
