### ISSUE TITLE
IANA service name for secure MQTT is not MQTTS

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/asyncapi#34]
IANA service name for secure MQTT is `secure-mqtt` and not `mqtts`.

https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=secure-mqtt

This:
```yaml
servers:
  - url: api.company.com
    scheme: mqtts
```

should become this:

```yaml
servers:
  - url: api.company.com
    scheme: secure-mqtt
```
