### ISSUE TITLE
It should have a way to specify protocol version

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/asyncapi#35]
For instance, AQMP 0-9-1 differs a lot from AMQP 1.0. It's actually a totally new protocol.

**Example:**

```yaml
servers:
  - url: api.company.com
    scheme: amqp
    schemeVersion: '1.0'
```

**Another example:**

```yaml
servers:
  - url: api.company.com
    scheme: kafka
    schemeVersion: '0.10.0'
```
