### ISSUE TITLE
[Specification missmatch]: MessageObject.traits, OperationObject.traits

### ISSUE THREAD

**Issue by Pakisan** [asyncapi/asyncapi#385]
#### Describe the bug
Description mismatch for `MessageObject`, `OperationObject` traits

#### How to Reproduce
Example:
[OperationObject](https://www.asyncapi.com/docs/specifications/2.0.0/#a-name-operationobject-a-operation-object) example: 
```yaml
{
  "operationId": "registerUser",
  "summary": "Action to sign a user up.",
  "description": "A longer description",
  "tags": [
    { "name": "user" },
    { "name": "signup" },
    { "name": "register" }
  ],
  "message": {
    "headers": {
      "type": "object",
      "properties": {
        "applicationInstanceId": {
          "description": "Unique identifier for a given instance of the publishing application",
          "type": "string"
        }
      }
    },
    "payload": {
      "type": "object",
      "properties": {
        "user": {
          "$ref": "#/components/schemas/userCreate"
        },
        "signup": {
          "$ref": "#/components/schemas/signup"
        }
      }
    }
  },
  "bindings": {
    "amqp": {
      "ack": false
    },
  },
  "traits": [
    { "$ref": "#/components/operationTraits/kafka" }
  ]
}
```

#### Expected behavior
Should be `*TraitObject` or `ReferenceObject`
