### ISSUE TITLE
Message object examples facet has a wrong type

### ISSUE THREAD

**Issue by BlockLucas** [asyncapi/asyncapi#410]
Issue part of #397

It’s an array of Maps, it should be only a Map. Message trait objects have the same problem.
https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#message-object
https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#message-trait-object

**Comment by derberg** [comment]
Hi. Why `examples` should not be an array. The description is clear that it should be an array, schema too https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/schema.json#L692. Or you have something different in mind?

**Comment by gutee** [comment]
Hi @derberg, if examples is an array it is wrongly expressed. Imagine a payload schema of type string only. How would the examples be expressed with the syntax as it is today? An array of map from string to the example (the message object with a json schema):

```
payload:
  type: string
examples:
  -  someName: theExample
  -  someOtherName: anotherExample
      otherNameItemInThisArrayItem: lastExample
```

If we want examples to be named, the type should be only a map of string to the example, so that names are not repeated and we don't have the confusion happening in the previous example (exactly as OAS and RAML do this):

```
payload:
  type: string
examples:
  someName: the Example
  someOtherName: anotherExample
  otherNameItemInThisArrayItem: lastExample
```

This is the correct approach using the `examples` keyword, just remove the array around the Map in the examples type.

**Comment by fmvilas** [comment]
I think what's wrong here is to say that it should be an array of Maps. It actually should be an array of "any". So to compare with your example, @gutee, it should be:

```yaml
payload:
  type: string
examples:
  - the Example
  - anotherExample
  - lastExample
```

This should be fixed on the [human-readable spec](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#messageObjectExamples) and also on the [machine-readable spec](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/schema.json#L693). It would be great to take the opportunity to mention that whatever "any" is, it has to match the type defined on `payload`.
