### ISSUE TITLE
Consideration: Protocol specific message objects

### ISSUE THREAD

**Issue by gmr** [asyncapi/asyncapi#42]
AMQP, STOMP, MQTT, and others all have variations in the message structure.

I wanted to suggest that you consider the idea of protocol specific message objects *or* protocol specific message object properties, that embrace the individuality and uniqueness of each protocol's message specification.

In addition, the variations between AMQP 0.9 and 1.0 are enough to warrant protocol version disambiguation.

Have you previously put any thought into this? As someone who's a fairly invested in AMQP 0.9, I'd love to see more detail in that area than what the spec currently provides.

**Comment by fmvilas** [comment]
That sounds like an excellent idea. Probably, we could accomplish it by extending messages' fields. Example:

```yaml
lightMeasured:
  summary: Inform about environmental lighting conditions for a particular streetlight.
  payload:
    type: object
    properties:
      lumens:
        type: integer
        minimum: 0
        description: Light intensity measured in lumens.
  amqp:
    version: "0.9.1"
    type: object
    properties:
      somethingUniqueForAMQP: something
```

There are many (and better) ways to do that but I'm leaving this here as a PoC. Is this what you mean?
