### ISSUE TITLE
Cleanup GitHub Actions workflows

### ISSUE THREAD

**Issue by derberg** [asyncapi/asyncapi#445]
**Context**

1. We want to make sure we have healthy community and people respec each other in GitHub. We want to monitor all comments in every repository and analyze sentiments to identify negative ones and get proper notification. Idea is to use GitHub Actions for it, to check sentiments with Google Natural Language API and post negative comments to Slack for review.

2. We manage community files in global `.github` repo, and we have GitHub Funding config file there too. As a result we need to cleanup all the repos to remove `.github/FUNDING.yml`

3. Start supporting new GitHub [pull request event](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target) that allows gives access to `GITHUB_TOKEN` with write access. Fix welcome contributors workflow is needed.

4. We want to automatically merge Pull Requests that are submitted by [Dependanbot](https://dependabot.com/). New workflow needs to be added, or if already existins it needs to be modified

**Description**

1. Add this workflow file called `sentiment-analysis.yml` to `.github/workflows` (create it if it doesn't exist yet) directory:
    ```yaml
    name: 'Sentiment Analysis'

    on: 
    issue_comment:
        types: 
        - created
        - edited
    issues:
        types:
        - opened
        - edited
    pull_request:
        types:
        - opened
        - edited
    pull_request_review:
        types:
        - submitted
        - edited
    pull_request_review_comment:
        types:
        - created
        - edited
    jobs:
    test:
        name: Checking sentiments
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Check sentiment
            uses: derberg/code-of-conduct-sentiment-analysis-github-action@v1
            id: sentiments
            with:
            gcp_key: ${{ secrets.GCP_KEY_SENTIMENT }} 
        - uses: someimportantcompany/github-actions-slack-message@v1
            # this step runs only if sentiment is a negative numner
            if: steps.sentiments.outputs.sentiment < 0
            with:
            webhook-url: ${{ secrets.SLACK_SENTIMENTS }}
            text: Here ${{steps.sentiments.outputs.source}} you can find a potential negative text that requires your attention as the sentiment analysis score is ${{steps.sentiments.outputs.sentiment}}
            color: orange
    ```
    Proper secrets are already added to GitHub organization so it is as simple as adding above file to workflows dir.
2. Remove `.github/FUNDING.yml` if it exists
3. If not done already rename `pull_request` from line 4 to `pull_request_target` in `.github/workflows/welcome-first-time-contrib.yml` file
4. Create new file called `automerge.yml` with the following content:
    ```yaml
    name: Automerge PR

    on:
    pull_request:
        types:
        - labeled
        - unlabeled
        - synchronize
        - opened
        - edited
        - ready_for_review
        - reopened
        - unlocked
    pull_request_review:
        types:
        - submitted
    check_suite: 
        types:
        - completed
    status: {}
    
    jobs:
    autoapprove:
        runs-on: ubuntu-latest
        steps:
        - name: Autoapproving
            uses: hmarr/auto-approve-action@v2.0.0
            if: github.actor == 'asyncapi-bot' || github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
            with:
            github-token: "${{ secrets.GITHUB_TOKEN }}"

    automerge:
        needs: [autoapprove]
        runs-on: ubuntu-latest
        steps:
        - name: Automerging
            uses: pascalgn/automerge-action@v0.7.5
            if: github.actor == 'asyncapi-bot' || github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
            env:
            GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
            GITHUB_LOGIN: asyncapi-bot
            MERGE_LABELS: ""
            MERGE_METHOD: "squash"
            MERGE_COMMIT_MESSAGE: "pull-request-title"
            MERGE_RETRIES: "10"
            MERGE_RETRY_SLEEP: "10000"
    ```
    If the repository already has a file called `automerge-release-pr-bump.yml` than rename it and adjust `if` statements to check `github.actor == 'asyncapi-bot' || github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'` instead of `github.actor == 'asyncapi-bot'`
