### ISSUE TITLE
Question: Publish or Subscribe multiple events from same channel

### ISSUE THREAD

**Issue by HenningRoigaard** [asyncapi/asyncapi#460]
How do you specify that an application consumes or produces multiple messages to the same channel? I think that I may be reading the specification wrong or somehow missing something obvious. Let’s assume that my application subscribes to two messages, M1 and M2, in the Kafka topic MyTopic.

Option 1: Repeating the channel 

```
Channels:
  MyTopic:
    subscribe:
      $ref: …/M1
  MyTopic:
    subscribe:
      $ref: …/M2
```
I assume that a channel cannot be repeated as it is listed as a Patterned field, and Patterned fields can only be repeated if unique. However, the spec also says that Patterned fields are defined using regexp, and channel name doesn’t have one (the field pattern is listed as ‘{channel}’).

Option 2: Repeating the Subscribe/Publish operation

```
Channels:
  MyTopic:
    subscribe:
      $ref: …/M1
    subscribe:
      $ref: …/M2
```
The specification says that “Patterned fields can have multiple occurrences as long as each has a unique name”, but it doesn’t say whether fixed fields like “subscribe” can?

Option 3: using the _oneof_

```
Channels:
  MyTopic:
    subscribe:
      messages:
        oneof:
          -   $ref: …/M1
          -   $ref: …/M2
```
This one bugs me, as one subscribe or publish element seem to define one operation of sorts, e.g., the element has one summary and one description. Each of the messages M1 and M2 may represent very different operations, deserving of their own summaries and descriptions.

What is the proper way to do this?
