### ISSUE TITLE
[BUG] Examples on Message Object - spec and parser/playground inconsistent

### ISSUE THREAD

**Issue by 195858** [asyncapi/asyncapi#501]
The behaviour of the parser and api playground seems inconsistent with the spec.

The MessageObject spec (https://www.asyncapi.com/docs/specifications/2.0.0#messageObject) documents `examples` as a string/any map - `\[Map\[`string`, `any`\]\]`

However this format is not accepted by the parser.

As an example - see the microcks version of an Async API document at https://microcks.io/documentation/using/asyncapi/
```
examples:
  - laurent:
      summary: Example for Laurent user
      payload: |-
        {"id": "{{randomString(32)}}", "sendAt": "{{now()}}", "fullName": "Laurent Broudoux", "email": "laurent@microcks.io", "age": 41}
  - john:
      summary: Example for John Doe user
      payload:
        id: '{{randomString(32)}}'
        sendAt: '{{now()}}'
        fullName: John Doe
        email: john@microcks.io
        age: 36
```

We have an array of examples, each with a key (laurent, john) and payload.

Find two full async api specs below that declare `examples` in different ways.

This doesn't work in playground/parser:
```
      examples:
      - ex1:
        payload: "test"
      - ex2:
        payload: "test2"
```
This works:
```
      examples:
      - payload: "test"
      - payload: "test2"
```

Here's a short example of what I believe would be a valid spec using the same format as above
If I paste this into the async api playground I get a number of error messages (I'll add these to the end for readability).
```
asyncapi: '2.0.0'
info:
  title: Examples API
  version: '1.0.0'
  description: |
    Testing message examples
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
defaultContentType: application/json
servers:
  dev-amqp:
    protocol: amqp
    protocolVersion: 3.1.1
    url: amqp://localhost:5672

components:
  messages:
    msg1:
      payload:
        type: string
      examples:
      - ex1:
        payload: "test"
      - ex2:
        payload: "test2"
  
channels:
  channel/4:
    publish:
      summary: a test.
      operationId: onMessage
      message:
        $ref: '#/components/messages/msg1'
```

If we change the spec slightly to omit the `string` key of the array the spec is valid:
```
asyncapi: '2.0.0'
info:
  title: Examples API
  version: '1.0.0'
  description: |
    Testing message examples
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
defaultContentType: application/json
servers:
  dev-amqp:
    protocol: amqp
    protocolVersion: 3.1.1
    url: amqp://localhost:5672

components:
  messages:
    msg1:
      payload:
        type: string
      examples:
      - payload: "test"
      - payload: "test2"
  
channels:
  channel/4:
    publish:
      summary: a test.
      operationId: onMessage
      message:
        $ref: '#/components/messages/msg1'
```
Errors in playground:
```
[
  "/channels/channel~14/publish/message should have required property '$ref' at line 33, column 7",
  "/channels/channel~14/publish/message should NOT have additional properties at line 33, column 7",
  "/channels/channel~14/publish/message should NOT have additional properties at line 33, column 7",
  "/channels/channel~14/publish/message should have required property 'oneOf' at line 33, column 7",
  "/channels/channel~14/publish/message/examples/0 should NOT have additional properties",
  "/channels/channel~14/publish/message/examples/1 should NOT have additional properties",
  "/channels/channel~14/publish/message should match exactly one schema in oneOf at line 33, column 7",
  "/channels/channel~14/publish/message should match exactly one schema in oneOf at line 33, column 7",
  "/components/messages/msg1 should have required property '$ref' at line 19, column 5",
  "/components/messages/msg1 should NOT have additional properties at line 19, column 5",
  "/components/messages/msg1 should NOT have additional properties at line 19, column 5",
  "/components/messages/msg1 should have required property 'oneOf' at line 19, column 5",
  "/components/messages/msg1/examples/0 should NOT have additional properties at line 23, column 9",
  "/components/messages/msg1/examples/1 should NOT have additional properties at line 25, column 9",
  "/components/messages/msg1 should match exactly one schema in oneOf at line 19, column 5",
  "/components/messages/msg1 should match exactly one schema in oneOf at line 19, column 5"
]
```

**Comment by derberg** [comment]
@195858 sorry for the confusion, the most accurate description atm is here https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#messageObject

What is described in Microcks docs is not yet part of the spec. It is how it will be once [this](https://github.com/asyncapi/asyncapi/issues/329) feature request from Microcks founder is processed.

cc @lbroudoux

**Comment by 195858** [comment]
Hi @derberg,

I think there is something out of sync between the spec and the node.js asyncapi parser ...

On the link you added - the examples element is described as a map of {string, any}.

However the async api playground and the parser will NOT parse a map, it expects an array.

According to the spec you linked this should be valid:
```
      examples:
      - ex1:
        payload: "test"
      - ex2:
        payload: "test2"
```
where ex1, ex2 are the string keys in the map, payload is the "any" map entry.

But the parser will not accept this. It parses an array of "any" though.

The question is: is the spec right and the parser wrong or vice versa?

Ignore the microcks example - I just quoted it as it is one of the very few async api examples that uses the "examples" element on the message object.

**Comment by derberg** [comment]
@195858 this is map of string and any, while string must be payload or header, so:
```
examples:
  - headers:
      correlationId: my-correlation-id
      applicationInstanceId: myInstanceId
    payload:
      user:
        someUserKey: someUserValue
      signup:
        someSignupKey: someSignupValue
```
