### ISSUE TITLE
Allow for payload media types to be documented

### ISSUE THREAD

**Issue by wout3r** [asyncapi/asyncapi#54]
Right now, AsyncAPI is missing a way to document the payloads' media type (e.g., JSON, XML, ...). 
Can the specification be enriched to make this possible?

The approach for documenting media types could be similar to the one proposed in the OpenAPI specifications (v2 & v3):

1. The AsyncAPI Object could be extended with a 'defaultPayloadMediaType' property that allows to specify the default payload media type (e.g., with "application/json" as default value).

2. The type of the Message.payload property could be changed to "Map[string (media type), Schema Object] | Schema Object",  which allows the default payload media type to be overridden at the payload-level.

This would allow API specifications such as:
```
asyncapi: '1.0.0'
...
defaultPayloadMediaType: text/xml

topics:
  X:
    publish:
      payload:
        type: object
        properties:
          ...

  J:
    publish:
      payload:
        application/json:
          type: object
          properties:
            ...

  O:
    subscribe:
      payload:
        application/x-java-serialized-object:
          type: object
          properties:
            ...
```

Thanks in advance for considering this feature request!
