### ISSUE TITLE
attribute to identify function to call

### ISSUE THREAD

**Issue by chris3081** [asyncapi/asyncapi#77]
So the idea is to have an attribute that can identify what attribute to call when a message is pulled from the queue. 

```
components:
  messages:
     HelloWorld:
       summary: Hello World
       payload:
         type: object
         properties:
           arga:
             type: string
           argb:
             type: string
       x-operation-id: "helloworld.say"
```

Where Helloworld is a python file and say is a method in it

A sample function for calling the operation would look like this
```
    def callmethod(self, message, **kwargs):
        try:
            if 'x-osperation-id' in self._config['components']['messages'][message].keys():
                methodlookup = self._config['components']['messages'][message]['x-operation-id']
                library, func = methodlookup.rsplit('.', 1)
                i = importlib.import_module(library)
                method_to_call = getattr(i, func)
                return method_to_call(**kwargs)
        except Exception as e:
            raise e
        return None
```

**Comment by fmvilas** [comment]
Thanks for raising the issue @chris3081.

I guess the debate here is if we should standardize `operationId`. My bet is that we should do it in order to increase compatibility with OpenAPI 3. However, it's not that simple in AsyncAPI because there's no such thing as an "operation object". The `publish`/`subscribe` operations are, in fact, message objects. So adding `operationId` as an attribute of "message" would couple messages to operations, 1:1, and that's an architecture decision the spec should not be imposing.

That said, we can rework the spec in the next major version to have operation objects separate from messages. Something like the following:

```yaml
publish:
  operationId: sayHello
  summary: Says hello.
  description: Publish a message to say hello.
  message:
   summary: A hello message
   payload:
     type: object
     properties:
       arga:
         type: string
       argb:
         type: string
```

This would be more similar to OpenAPI 3. But, just to make it clear, **this should be done in a next major version as it's a breaking change**. In the meantime, your solution looks good enough to bypass the limitation.
